export enum TicketType {
    GENERAL = 'GENERAL',
    TECHNICAL = 'TECHNICAL',
    BILLING = 'BILLING',
    MEDICAL = 'MEDICAL',
    APPOINTMENT = 'APPOINTMENT',
    ACCESS = 'ACCESS',
    COMPLAINT = 'COMPLAINT',
    FEEDBACK = 'FEEDBACK',
} 